-- ------------- Creating tables : first parent, then the child ---------------
-- ----------------------------------------------------------------------------

CONNECT TO LABSV3;

-- Create table post
CREATE TABLE DB2ADMIN.POST (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	NAME VARCHAR (56) NOT NULL,
	SALARY BIGINT,
	UNIT_NUMBER INTEGER,
	PRIMARY KEY (ID),
	UNIQUE (NAME)) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.POST IS 'Таблица штатов';

-- Create table employee
CREATE TABLE DB2ADMIN.EMPLOYEE (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	FULL_NAME VARCHAR (60) NOT NULL,
	REPORT_CARD_NUMBER VARCHAR (8) NOT NULL,
	ADDRESS VARCHAR (130),
	PHONE VARCHAR (20),
	POSTID INTEGER,
	PRIMARY KEY (ID),
	UNIQUE (REPORT_CARD_NUMBER),
	FOREIGN KEY (POSTID) 
		REFERENCES DB2ADMIN.POST (ID)
		ON DELETE SET NULL
		ON UPDATE RESTRICT
		ENFORCED DISABLE QUERY OPTIMIZATION) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.EMPLOYEE IS 'Таблица персонала';

-- Create table deposit
CREATE TABLE DB2ADMIN.DEPOSIT (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	NAME VARCHAR (70) NOT NULL,
	CURRENCY VARCHAR (10) NOT NULL,
	PRIMARY KEY (ID)) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.DEPOSIT IS 'Таблица вкладов';

-- Create table client
CREATE TABLE DB2ADMIN.CLIENT (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	FULL_NAME VARCHAR (60) NOT NULL,
	ADDRESS VARCHAR (130),
	ACCOUNT_NUMBER VARCHAR (20) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	DEPOSITID INTEGER,
	PRIMARY KEY (ID),
	UNIQUE (ACCOUNT_NUMBER),
	FOREIGN KEY (DEPOSITID)
		REFERENCES DB2ADMIN.DEPOSIT (ID)
		ON DELETE SET NULL
		ON UPDATE RESTRICT
		ENFORCED DISABLE QUERY OPTIMIZATION) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.CLIENT IS 'Таблица клиентов';

-- Create table operation
CREATE TABLE DB2ADMIN.OPERATION (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	NAME VARCHAR (40) NOT NULL,
	PRIMARY KEY (ID),
	UNIQUE (NAME)) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.OPERATION IS 'Таблица операций';

-- Create table transfer
CREATE TABLE DB2ADMIN.TRANSFER (
	ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 0, INCREMENT BY 1, NO CACHE),
	TRANSFER_DATE DATE NOT NULL,
	CLIENTID INTEGER NOT NULL,
	OPERATIONID INTEGER,
	EMPLOYEEID INTEGER NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLIENTID) 
		REFERENCES DB2ADMIN.CLIENT (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
		ENFORCED DISABLE QUERY OPTIMIZATION,
	FOREIGN KEY (OPERATIONID)
		REFERENCES DB2ADMIN.OPERATION (ID)
		ON DELETE SET NULL
		ON UPDATE RESTRICT
		ENFORCED DISABLE QUERY OPTIMIZATION,
	FOREIGN KEY (EMPLOYEEID)
		REFERENCES DB2ADMIN.EMPLOYEE (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT
		ENFORCED  DISABLE QUERY OPTIMIZATION) IN USERSPACE1;
COMMENT ON TABLE DB2ADMIN.TRANSFER IS 'Таблица движений денег';

CONNECT RESET;
