-- ---------- Filling the tables: first the parent, then the child ------------
-- ----------------------------------------------------------------------------

CONNECT TO LABSV3;

-- Filling table post

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Управляющий', 25000000, 1);

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Заместитель управляющего', 20000000, 3);

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Начальник отдела', 18000000, 4);

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Заместитель начальника отдела', 16000000, 8);

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Специалист', 14000000, 8);

INSERT INTO POST (NAME, SALARY, UNIT_NUMBER)
VALUES ('Опперационист', 10000000, 18);

-- Filling table employee

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Никифоров Владислав Викторович', '456752', 
'Гомель, ул.Радужная, д.15, кв.10', '+375(29)672-54-07', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Управляющий'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Рогозов Андрей Владимирович', '456753', 
NULL, '+375(29)678-74-27', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Заместитель управляющего'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Кириченко Иван Николаевич', '456755', 
'Гомель, ул.Владимирова, д.11', NULL, 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Начальник отдела'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Бурикин Николай Николаевич', '456758', 
'Гомель, ул.Ленина, д.8, кв.1', '+375(33)875-57-05', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Заместитель начальника отдела'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Силиванова Елена Михайловна', '456760', 
'Гомель, ул.Кожара, д.87, кв.7', '+375(44)784-94-07', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Опперационист'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Савенок Ольга Анатольевна', '456761', 
'Гомель, ул.Ленина, д.18, кв.57', '+375(29)879-87-89', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Опперационист'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Лашкевич Анна Николаевна', '456763', 
'Гомель, ул.Хижнякова, д.1', '+375(29)997-00-75', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Опперационист'));

INSERT INTO EMPLOYEE (FULL_NAME, REPORT_CARD_NUMBER, ADDRESS, PHONE, POSTID)
VALUES ('Сидоренко Сергей Евгеньевич', '456766', 
'Гомель, ул.Кравченко, д.75', '+375(29)914-40-77', 
(SELECT POST.ID FROM POST WHERE POST.NAME = 'Опперационист'));

-- Filling table deposit

INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Сберегательный', 'BYR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Безотзывный', 'RUB');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Безотзывный Новый', 'USD');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Классик', 'BYR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Классик Плюс', 'EUR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Пенсионный', 'BYR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Гарантированный доход', 'USD');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Премиально-накопительный "Детский"', 'EUR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('До востребования', 'BYR');
INSERT INTO DEPOSIT (NAME, CURRENCY) VALUES ('Попечение', 'BYR');

-- Filling table client

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Попова Ксения Владимировна', 'Гомель, ул.Лазурная, д.1, кв.15', 'AB9635',
'2015-04-16', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Безотзывный'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Бучик Татьяна Михайловна', NULL, 'AB9628',
'2015-09-28', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Пенсионный'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Сириченко Сергей Сергеевич', 'Гомель, ул.Ленина, д.10, кв.1', 'AB9654',
'2015-01-20', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Классик'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Ашарчук Кристина Игоревна', 'Гомель, ул.Международная, д.5, кв.67', 'AB9657',
'2014-01-16', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Классик Плюс'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Казаков Игорь Евгеньевич', 'Гомель, ул.Чернякова, д.54, кв.12', 'AB9677',
'2015-12-15', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Гарантированный доход'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Филипенко Егор Александрович', 'Гомель, ул.Ленина, д.57, кв.10', 'AB9674',
'2015-09-16', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Безотзывный Новый'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Андрасюк Анна Александровна', NULL, 'AB9612',
'2014-11-10', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Попечение'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Левченко Михаил Андреевич', 'Гомель, ул.Химиков, д.189, кв.57', 'AB9678',
'2015-04-21', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Пенсионный'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Тихончук Дмитрий Иванович', 'Гомель, ул.Химиков, д.14, кв.1', 'AB9607',
'2015-04-18', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'До востребования'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Коржов Алексей Алксеевич', 'Гомель, ул.Кожара, д.1, кв.77', 'AB9630',
'2015-04-25', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Безотзывный'));

INSERT INTO CLIENT (FULL_NAME, ADDRESS, ACCOUNT_NUMBER, CREATION_DATE, DEPOSITID)
VALUES ('Куприенко Владимир Фёдорович', 'Гомель, ул.Речная, д.78', 'AB9629',
'2014-08-13', (SELECT DEPOSIT.ID FROM DEPOSIT WHERE DEPOSIT.NAME = 'Сберегательный'));

-- Filling table operation

INSERT INTO OPERATION (NAME) VALUES ('Пополнение');
INSERT INTO OPERATION (NAME) VALUES ('Частичное снятие');
INSERT INTO OPERATION (NAME) VALUES ('Начисление процентов');
INSERT INTO OPERATION (NAME) VALUES ('Закрытие');

-- Filling table transfer

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2016-01-14', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Андрасюк Анна Александровна'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Сидоренко Сергей Евгеньевич'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-08-01', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Попова Ксения Владимировна'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Савенок Ольга Анатольевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-11-13', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Бучик Татьяна Михайловна'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Начисление процентов'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Лашкевич Анна Николаевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-10-18', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Попова Ксения Владимировна'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Частичное снятие'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Сидоренко Сергей Евгеньевич'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-01-16', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Ашарчук Кристина Игоревна'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Закрытие'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Сидоренко Сергей Евгеньевич'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2016-01-10', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Казаков Игорь Евгеньевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Лашкевич Анна Николаевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-12-16', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Филипенко Егор Александрович'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Начисление процентов'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Савенок Ольга Анатольевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-09-21', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Левченко Михаил Андреевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Силиванова Елена Михайловна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-11-14', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Левченко Михаил Андреевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Сидоренко Сергей Евгеньевич'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2016-01-10', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Левченко Михаил Андреевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Закрытие'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Силиванова Елена Михайловна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-09-01', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Тихончук Дмитрий Иванович'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Начисление процентов'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Силиванова Елена Михайловна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-12-11', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Тихончук Дмитрий Иванович'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Закрытие'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Лашкевич Анна Николаевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-05-01', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Коржов Алексей Алксеевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Лашкевич Анна Николаевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-10-14', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Коржов Алексей Алксеевич'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Пополнение'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Савенок Ольга Анатольевна'));

INSERT INTO TRANSFER (TRANSFER_DATE, CLIENTID, OPERATIONID, EMPLOYEEID)
VALUES ('2015-01-11', 
(SELECT CLIENT.ID FROM CLIENT WHERE CLIENT.FULL_NAME = 'Куприенко Владимир Фёдорович'), 
(SELECT OPERATION.ID FROM OPERATION WHERE OPERATION.NAME = 'Закрытие'),
(SELECT EMPLOYEE.ID FROM EMPLOYEE WHERE EMPLOYEE.FULL_NAME = 'Савенок Ольга Анатольевна'));

CONNECT RESET;
