-- ---------------------- Removing view-tables --------------------------------

CONNECT TO LABSV3;

DROP VIEW VIEW_CLIENT_DETAIL;
DROP VIEW VIEW_TRANSFER_DETAIL;
DROP VIEW VIEW_TRANSFER_FOR_2015;
DROP VIEW VIEW_CLOSE_DEPOSIT;
DROP VIEW VIEW_CLIENT_COUNT_OPERATION;

CONNECT RESET;
