-- ------ Removing tables, if they exist: first the child, then parent --------

CONNECT TO LABSV4;

DROP TABLE "VIKTOR BARANOV".SALE;
DROP TABLE "VIKTOR BARANOV".EMPLOYEE;
DROP TABLE "VIKTOR BARANOV".STORAGE;
DROP TABLE "VIKTOR BARANOV".PRODUCT;
DROP TABLE "VIKTOR BARANOV".POST;
DROP TABLE "VIKTOR BARANOV".CATEGORY;
DROP TABLE "VIKTOR BARANOV".BUYER;

CONNECT RESET;
