-- ----------------------------- Get data all tables --------------------------

CONNECT TO LABSV4;
SELECT * FROM BUYER;
SELECT * FROM CATEGORY;
SELECT * FROM EMPLOYEE;
SELECT * FROM POST;
SELECT * FROM PRODUCT;
SELECT * FROM SALE;
SELECT * FROM STORAGE;
CONNECT RESET;
