-- ---------------------- Removing view-tables --------------------------------

CONNECT TO LABSV4;

DROP VIEW "VIKTOR BARANOV".VIEW_EMPLOYEE_DETAIL;
DROP VIEW "VIKTOR BARANOV".VIEW_SALE_DETAIL;
DROP VIEW "VIKTOR BARANOV".VIEW_SALE_FOR_2015;
DROP VIEW "VIKTOR BARANOV".VIEW_SALE_FROM_MOGILEV;
DROP VIEW "VIKTOR BARANOV".VIEW_BUYER_PURCHASE_AMOUNT;

CONNECT RESET;
