-- --------------------- Create view tables for task 3 ------------------------
-- ----------------------------------------------------------------------------

CONNECT TO LABSV4;

-- 1. Создание view-таблицы сотрудников с указанной должность, категорией и ЗП
CREATE VIEW VIEW_EMPLOYEE_DETAIL AS 
	SELECT EMPLOYEE.ID, EMPLOYEE.FULL_NAME, EMPLOYEE.REPORT_CARD_NUMBER, 
	CATEGORY.NAME AS CATEGORY, POST.NAME AS POST, POST.SALARY 
	FROM EMPLOYEE, CATEGORY, POST
	WHERE EMPLOYEE.POSTID = POST.ID AND EMPLOYEE.CATEGORYID = CATEGORY.ID;

-- Тестовая выборка view-таблицы VIEW_EMPLOYEE_DETAIL
SELECT * FROM VIEW_EMPLOYEE_DETAIL;


-- 2. Создание view-таблицы продаж с указанным сотрудником, покупателем и изделием
CREATE VIEW VIEW_SALE_DETAIL AS
	SELECT SALE.ID, SALE.SALE_DATE, EMPLOYEE.FULL_NAME AS EMPLOYEE_NAME,
	PRODUCT.NAME AS PRODUCT, PRODUCT.PRICE, SALE.AMOUNT,
	BUYER.NAME AS BUYER
	FROM SALE, BUYER, EMPLOYEE, PRODUCT
	WHERE SALE.EMPLOYEEID = EMPLOYEE.ID AND SALE.BUYERID = BUYER.ID 
	AND SALE.PRODUCTID = PRODUCT.ID;

-- Тестовая выборка view-таблицы VIEW_SALE_DETAIL
SELECT * FROM VIEW_SALE_DETAIL;


-- 3. Создание view-таблицы продаж за 2015 год
CREATE VIEW VIEW_SALE_FOR_2015 AS
	SELECT SALE.ID, PRODUCT.NAME AS PRODUCT, SALE.SALE_DATE, 
	EMPLOYEE.FULL_NAME AS EMPLOYEE, BUYER.NAME AS BUYER
	FROM SALE, PRODUCT, EMPLOYEE, BUYER 
	WHERE SALE.EMPLOYEEID = EMPLOYEE.ID AND SALE.BUYERID = BUYER.ID 
	AND SALE.PRODUCTID = PRODUCT.ID 
	AND SALE.SALE_DATE BETWEEN '2015-01-01' AND '2015-12-31';

-- Тестовая выборка view-таблицы VIEW_SALE_FOR_2015
SELECT * FROM VIEW_SALE_FOR_2015;


-- 4. Создание view-таблицы покупателей из Могилёва
CREATE VIEW VIEW_SALE_FROM_MOGILEV AS
	SELECT BUYER.ID, BUYER.NAME, BUYER.ADDRESS FROM BUYER
	WHERE BUYER.ADDRESS LIKE '%г. Могилёв%';

-- Тестовая выборка view-таблицы VIEW_SALE_FROM_MOGILEV
SELECT * FROM VIEW_SALE_FROM_MOGILEV;


-- 5. Создание view-таблицы покупки с указанием суммы покупок каждого покупателя
CREATE VIEW VIEW_BUYER_PURCHASE_AMOUNT AS
	SELECT BUYER.NAME AS BUYER, PRODUCT.NAME AS PRODUCT, SALE.SALE_DATE, 
	SALE.AMOUNT * PRODUCT.PRICE AS PURCHASE_AMOUNT
	FROM BUYER, SALE, PRODUCT
	WHERE SALE.BUYERID = BUYER.ID AND SALE.PRODUCTID = PRODUCT.ID;

-- Тестовая выборка view-таблицы VIEW_BUYER_PURCHASE_AMOUNT
SELECT * FROM VIEW_BUYER_PURCHASE_AMOUNT;

CONNECT RESET;
