-- ------------------------ Removing stored procedures ------------------------

CONNECT TO LABSV4;

DROP PROCEDURE "VIKTOR BARANOV".GET_BUYERS_BY_ID;
DROP PROCEDURE "VIKTOR BARANOV".GET_CATEGORY_BY_EMPLOYEE;

CONNECT RESET;
